package edu.usfca.hs619.builders

import org.apache.uima.analysis_engine.AnalysisEngine
import org.apache.uima.jcas.JCas

/**
  * A contract every UIMA aggregate pipeline used for processing needs to follow.
  */

trait Builder {
  /**
    * This method returns the Analytical engine.
    * @return org.apache.uima.analysis_engine.AnalysisEngine
    */
  def getPipeline:AnalysisEngine

  /***
    * This method processes the JCAS generated by the engine for the text which needs to be processed.
    * @param text The text that needs to be processed. This is a String
    * @param jCas This which is passed to U(MA org.apache.uima.fit.pipeline.SimplePipeline.runPipeline
    * @param engine This the Analysis engine which was build using the getPipeline method
    */
  def processJCAS(text:String, jCas:JCas, engine:AnalysisEngine):Unit
}
